// Code generated by "stringer -trimprefix ENV -type=AppEnv appenv.go"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ENVlocal-0]
	_ = x[ENVdevelop-1]
}

const _AppEnv_name = "localdevelop"

var _AppEnv_index = [...]uint8{0, 5, 12}

func (i AppEnv) String() string {
	if i < 0 || i >= AppEnv(len(_AppEnv_index)-1) {
		return "AppEnv(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AppEnv_name[_AppEnv_index[i]:_AppEnv_index[i+1]]
}
